# Generated by Django 4.2 on 2023-08-29 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="notifications",
        ),
    ]
