FROM ubuntu:latest
FROM python:3.8-bullseye

# Install RabbitMQ
RUN apt-get update && apt-get install -y rabbitmq-server

# Set the working directory
WORKDIR /ElectroStock

# Install Python dependencies
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# Copy the Django project
COPY . .

# Expose the necessary ports
EXPOSE 5672

# Start RabbitMQ
CMD ["rabbitmq-server"]
